import {StyleSheet} from 'react-native';
import {
  black,
  blue,
  green,
  grey,
  grey2,
  grey3,
  grey4,
  grey5,
  grey6,
  white,
  white2,
  white3,
  yellow,
} from '../../../styles/Colors';

const eRequestStyles = StyleSheet.create({
  goBack: {
    justifyContent: 'center',
    alignContent: 'center',
  },
  requests: {
    marginTop: '2%',
    width: '100%',
    padding: 10,
  },
  selectedExercises: {
    marginTop: '2%',
    width: '100%',
    padding: 10,
  },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: grey5,
    padding: '5%',
    borderRadius: 20,
  },
  titleContent: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: white,
    borderRadius: 20,
    padding: '5%',
  },
  btnText: {
    color: white,
    fontSize: 18,
  },
  bodyPart: {
    backgroundColor: white,
    borderRadius: 20,
    padding: '5%',
    marginTop: '3%',
  },
  bodyPartText: {
    fontSize: 16,
  },
  description: {
    flex: 3,
    height: 160,
    width: '100%',
    backgroundColor: white,
    borderRadius: 20,
    padding: '5%',
    marginVertical: '3%',
  },
  cardFooter: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btn: {
    width: '60%',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: green,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: black,
  },
  exercisesContent: {
    flex: 1,
    width: '100%',
  },
  exerciseNameContent: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
  },
  exerciseDetailsContent: {
    flex: 10,
  },
  position: {
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: '3%',
    color: white,
  },
  exerciseName: {
    flex: 4,
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: '3%',
  },
  positionDrag: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'column',
    padding: '1%',
    marginRight: '3%',
    height: '100%',
  },
  positionDragBtn: {
    flex: 1,
    paddingVertical: '5%',
  },
  pickerExerciseContent: {
    flex: 3,
    backgroundColor: green,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 20,
    padding: '1%',
  },
  pickerExercise: {
    flex: 2,
    color: white,
  },
  inputExercise: {
    borderRadius: 15,
    flex: 1,
    backgroundColor: grey6,
    color: black,
  },
  exercisesCard: {
    width: '100%',
    backgroundColor: white,
    borderRadius: 20,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  selectedExercisesCard: {
    width: '100%',
    backgroundColor: white,
    borderRadius: 20,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
});
export default eRequestStyles;
