import {StyleSheet} from 'react-native';
import {
  black,
  black2,
  blue,
  green,
  grey,
  grey2,
  grey3,
  grey6,
  white,
  white2,
  white3,
  yellow,
} from './Colors';

const rankingStyles = StyleSheet.create({
  crown: {
    height: 70,
    width: 70,
  },
  rank: {
    fontSize: 32,
    fontWeight: '600',
    color: white,
  },
  username: {
    fontSize: 18,
    fontWeight: '600',
  },
  points: {
    fontSize: 26,
    fontWeight: '600',
    color: green,
  },
  header: {
    flex: 1,
    width: '100%',
    backgroundColor: black,
  },
  headerContent: {
    flex: 4,
    flexDirection: 'row',
    alignItems: 'center',
    margin: 15,
  },
  avatar: {
    width: 75,
    height: 75,
    borderRadius: 63,
    borderWidth: 4,
    borderColor: black,
    margin: 1,
  },
  user: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '20%',
    flex: 1,
  },
  top1: {
    alignSelf: 'flex-start',
    height: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  top3: {
    marginTop: 30,
    height: '100%',
    alignSelf: 'flex-end',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalUser: {
    fontSize: 26,
    fontWeight: '400',
    color: white,
  },
  top3username: {
    fontWeight: '400',
    color: white,
  },
  top3points: {
    fontSize: 24,
    fontWeight: '700',
    color: green,
  },
  avatarContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  avatar1: {
    width: 100,
    height: 100,
    borderRadius: 63,
    borderWidth: 6,
    borderColor: green,
  },
  avatar2: {
    width: 75,
    height: 75,
    borderRadius: 63,
    borderWidth: 4,
    borderColor: green,
  },
  avatar3: {
    width: 50,
    height: 50,
    borderRadius: 63,
    borderWidth: 2,
    borderColor: green,
  },
  name: {
    marginLeft: 3,
    fontSize: 22,
    color: white,
  },
  rankingContent: {
    flex: 5,
    backgroundColor: black,
  },
  userBadgeContent: {
    flex: 3,
    marginLeft: '10%',
  },
  userContent: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'space-between',
    backgroundColor: black,
  },
  userRankContent: {
    flexDirection: 'row',
  },
  modalBody: {
    alignSelf: 'center',
    marginTop: '10%',
    marginBottom: '10%',
    backgroundColor: black,
    flex: 2,
    width: '80%',
    alignItems: 'center',
  },
  badgesContent: {
    backgroundColor: grey,
    borderRadius: 30,
    justifyContent: 'center',
    alignContent: 'center',
    width: '100%',
    flex: 4,
  },
  badge: {
    flexWrap: 'wrap',
    borderRadius: 40,
    marginHorizontal: 3,
    marginTop: 5,
  },
  rankingList: {
    flex: 1,
    width: '100%',
  },
  card: {
    flexDirection: 'row',
    paddingTop: '2%',
    paddingBottom: '2%',
    paddingHorizontal: '4%',
    marginBottom: '1%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rankingItemContainer: {
    flex: 6,
    backgroundColor: grey6,
    borderRadius: 30,
    flexDirection: 'row',
    paddingRight: '5%',
  },
  rankingItemContent: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  rankingHeader: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    flexDirection: 'row',
    paddingVertical: '1%',
    borderBottomWidth: 2,
    borderColor: black,
  },
  openBadges: {
    position: 'absolute',
    top: 5,
    right: 5,
  },
  leaderboard: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankingHeaderText: {
    marginLeft: 3,
    fontSize: 20,
    color: white,
    fontWeight: '600',
  },
  rankingHeaderMonth: {
    marginLeft: 3,
    fontSize: 16,
    color: white,
    fontWeight: '400',
  },
  avatarItem: {
    width: 60,
    height: 60,
    borderRadius: 63,
  },
});

export default rankingStyles;
