import {StyleSheet} from 'react-native';
import {
  black,
  black2,
  blue,
  green,
  grey,
  grey2,
  grey3,
  grey6,
  white,
  white2,
  white3,
  yellow,
} from './Colors';
import {RFValue} from 'react-native-responsive-fontsize';

const rankingStyles = StyleSheet.create({
  crown: {
    height: RFValue(70),
    width: RFValue(70),
  },
  rank: {
    fontSize: RFValue(32),
    fontWeight: '600',
    color: white,
  },
  username: {
    fontSize: RFValue(18),
    fontWeight: '600',
  },
  points: {
    fontSize: RFValue(26),
    fontWeight: '600',
    color: green,
  },
  header: {
    flex: 1,
    width: '100%',
    backgroundColor: black,
  },
  headerContent: {
    flex: 4,
    flexDirection: 'row',
    alignItems: 'center',
    margin: RFValue(15),
  },
  avatar: {
    width: RFValue(75),
    height: RFValue(75),
    borderRadius: RFValue(63),
    borderWidth: RFValue(4),
    borderColor: black,
    margin: 1,
  },
  user: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '20%',
    flex: 1,
  },
  top1: {
    alignSelf: 'flex-start',
    height: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  top3: {
    marginTop: RFValue(30),
    height: '100%',
    alignSelf: 'flex-end',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalUser: {
    fontSize: RFValue(26),
    fontWeight: '400',
    color: white,
  },
  top3username: {
    fontSize: RFValue(18),
    fontWeight: '400',
    color: white,
  },
  top3points: {
    fontSize: RFValue(24),
    fontWeight: '700',
    color: green,
  },
  avatarContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  avatar1: {
    width: RFValue(100),
    height: RFValue(100),
    borderRadius: RFValue(63),
    borderWidth: RFValue(6),
    borderColor: green,
  },
  avatar2: {
    width: RFValue(75),
    height: RFValue(75),
    borderRadius: RFValue(63),
    borderWidth: RFValue(4),
    borderColor: green,
  },
  avatar3: {
    width: RFValue(50),
    height: RFValue(50),
    borderRadius: RFValue(63),
    borderWidth: RFValue(2),
    borderColor: green,
  },
  name: {
    marginLeft: RFValue(3),
    fontSize: RFValue(22),
    color: white,
  },
  rankingContent: {
    flex: 5,
    backgroundColor: black,
  },
  userBadgeContent: {
    flex: 3,
    marginLeft: '10%',
  },
  userContent: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'space-between',
    backgroundColor: black,
  },
  userRankContent: {
    flexDirection: 'row',
  },
  modalBody: {
    alignSelf: 'center',
    marginTop: '10%',
    marginBottom: '10%',
    backgroundColor: black,
    flex: 2,
    width: '80%',
    alignItems: 'center',
  },
  badgesContent: {
    backgroundColor: grey,
    borderRadius: RFValue(30),
    justifyContent: 'center',
    alignContent: 'center',
    width: '100%',
    flex: 3,
  },
  badge: {
    flexWrap: 'wrap',
    borderRadius: RFValue(40),
    marginHorizontal: RFValue(3),
    marginTop: RFValue(5),
  },
  rankingList: {
    flex: 1,
    width: '100%',
  },
  card: {
    flexDirection: 'row',
    paddingTop: '2%',
    paddingBottom: '2%',
    paddingHorizontal: '4%',
    marginBottom: '1%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rankingItemContainer: {
    flex: 6,
    backgroundColor: grey6,
    borderRadius: RFValue(30),
    flexDirection: 'row',
    paddingRight: '5%',
  },
  rankingItemContent: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  rankingHeader: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    flexDirection: 'row',
    paddingVertical: '1%',
    borderBottomWidth: RFValue(2),
    borderColor: black,
  },
  openBadges: {
    position: 'absolute',
    top: RFValue(5),
    right: RFValue(5),
  },
  leaderboard: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankingHeaderText: {
    marginLeft: 3,
    fontSize: RFValue(20),
    color: white,
    fontWeight: '600',
  },
  rankingHeaderMonth: {
    marginLeft: 3,
    fontSize: RFValue(16),
    color: white,
    fontWeight: '400',
  },
  avatarItem: {
    width: RFValue(60),
    height: RFValue(60),
    borderRadius: RFValue(63),
  },
});

export default rankingStyles;
